# Generated by Django 3.2.4 on 2021-06-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_no', models.TextField()),
                ('Location', models.TextField()),
                ('end_user', models.TextField()),
                ('description', models.TextField()),
                ('brand', models.TextField()),
                ('unit_price', models.FloatField()),
                ('date_purchase', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
