# Generated by Django 3.2.3 on 2021-07-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='date_purchase',
            field=models.DateTimeField(),
        ),
    ]
