# Generated by Django 3.2.5 on 2021-07-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('node_id', models.CharField(max_length=2)),
                ('loc', models.CharField(max_length=10)),
                ('temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hum', models.DecimalField(decimal_places=2, max_digits=5)),
                ('light', models.DecimalField(decimal_places=2, max_digits=5)),
                ('snd', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
